const defaultSongs = [
    {
      name: "Nos Siguen Pegando Abajo",
      album: "Clics modernos",
      artist: "Charly García",
      bg_color: "#4cb8f5",
      url: "/audios/Nos Siguen Pegando Abajo.mp3",
      id: 0,
    },
    {
      name: "Promesas Sobre El Bidet",
      album: "Piano Bar",
      artist: "Charly García",
      bg_color: "#a6e630",
      url: "/audios/Promesas Sobre El Bidet.mp3",
      id: 1,
    },
    {
      name: "Hablando a Tu Corazón",
      album: "Tango",
      artist: "Charly García",
      bg_color: "#f5e82f",
      url: "/audios/Hablando a Tu Corazon.mp3",
      id: 2,
    },
    {
      name: "No Voy en Tren",
      album: "Parte de la religión",
      artist: "Charly García",
      bg_color: "#E75776",
      url: "/audios/No Voy en Tren.mp3",
      id: 3,
    },
    {
      name: "La Grasa de las Capitales",
      album: "La Grasa de las Capitales",
      artist: "Serú Girán",
      bg_color: "#E75776",
      url: "/audios/La Grasa de las Capitales.mp3",
      id: 4,
    },
    {
      name: "La Grasa de las Capitales",
      album: "La Grasa de las Capitales",
      artist: "Serú Girán",
      bg_color: "#E75776",
      url: "/audios/La Grasa de las Capitales.mp3",
      id: 5,
    },
    {
      name: "La Grasa de las Capitales",
      album: "La Grasa de las Capitales",
      artist: "Serú Girán",
      bg_color: "#E75776",
      url: "/audios/La Grasa de las Capitales.mp3",
      id: 6,
    },
    {
      name: "La Grasa de las Capitales",
      album: "La Grasa de las Capitales",
      artist: "Serú Girán",
      bg_color: "#E75776",
      url: "/audios/La Grasa de las Capitales.mp3",
      id: 7,
    },
    {
      name: "La Grasa de las Capitales",
      album: "La Grasa de las Capitales",
      artist: "Serú Girán",
      bg_color: "#E75776",
      url: "/audios/La Grasa de las Capitales.mp3",
      id: 8,
    },
    {
      name: "La Grasa de las Capitales",
      album: "La Grasa de las Capitales",
      artist: "Serú Girán",
      bg_color: "#E75776",
      url: "/audios/La Grasa de las Capitales.mp3",
      id: 9,
    },
  ]

export default defaultSongs;
